excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://serralvo.co
title: Fabricio Serralvo
email: fabricio.serralvo@gmail.com
author: Fabricio
description: 
paginate: 5
google_analytics: UA-65004285-1