excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://serralvo.github.io
title: Fabricio Serralvo
email: fabricio.serralvo@gmail.com
author: Fabricio
description: 
paginate: 5
google_analytics: 